# Autogenerated from /Users/franco/Documents/Projects/mlir-tut-impl/tests/lit.cmake.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


config.llvm_tools_dir = lit_config.substitute("/opt/homebrew/opt/llvm@19/bin")
config.mlir_obj_dir = "/Users/franco/Documents/Projects/mlir-tut-impl/build-dir"
config.llvm_shlib_ext = ""
config.project_binary_dir = "/Users/franco/Documents/Projects/mlir-tut-impl/build-dir"
config.project_source_dir = "/Users/franco/Documents/Projects/mlir-tut-impl"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/Users/franco/Documents/Projects/mlir-tut-impl/tests/lit.cmake.cfg.py")
